stages:
    - build
    - test
    - deploy

.base-rules:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always
    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: never

.backend-common:
    rules:
        - changes:
            - 'backend/**/*'

backend-build-first-job:
    stage: build
    extends: 
        - .backend-common
        - .base-rules
    image:  maven:latest
    script:
        - mvn -f backend/api-series/pom.xml clean install
        - mvn -f backend/api-movie/pom.xml clean install

    artifacts:
        expire_in: 1 week
        paths:
            - backend/api-series/target/api-series-0.0.1-SNAPSHOT.jar
            - backend/api-movie/target/api-movie-0.0.1-SNAPSHOT.jar

backend-build-second-job:
    stage: build
    extends: 
        - .backend-common
        - .base-rules
    image:  maven:latest
    script:
        - mvn -f backend/ms-config-server/pom.xml clean install
        - mvn -f backend/ms-eureka-server/pom.xml clean install
        - mvn -f backend/ms-gateway-server/pom.xml clean install
        - mvn -f backend/users-stack/ApiUsers/pom.xml clean install
    artifacts:
        expire_in: 1 week
        paths:
            - backend/ms-config-server/target/ms-config-server-0.0.1-SNAPSHOT.jar
            - backend/ms-eureka-server/target/ms-eureka-server-0.0.1-SNAPSHOT.jar
            - backend/ms-gateway-server/target/ms-gateway-server-0.0.1-SNAPSHOT.jar
            - backend/users-stack/ApiUsers/target/ApiUsers-0.0.1-SNAPSHOT.jar

backend-test-job:
    extends: 
        - .backend-common
        - .base-rules
    stage: test
    script:
        - echo "Testing backend"

deploy-job:
    stage: deploy
    image: alpine:3.11
    extends: 
        - .backend-common
        - .base-rules
    before_script:
        - apk update && apk add openssh-client bash
        - mkdir -p ~/.ssh
        - eval $(ssh-agent -s)
        - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
        - touch ~/.ssh/config
        - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
        - ssh-keyscan -H $DEPLOY_SERVER_IP >> ~/.ssh/known_hosts
        - ssh-keyscan -H $CONFIG_SERVER_IP >> ~/.ssh/known_hosts
        - ssh-keyscan -H $EUREKA_SERVER_IP >> ~/.ssh/known_hosts
        - ssh-keyscan -H $GATEWAY_SERVER_IP >> ~/.ssh/known_hosts
        - ssh-keyscan -H $USERS_SERVER_IP >> ~/.ssh/known_hosts
    script:
#  - CONFIG SERVER
        - ssh ubuntu@$CONFIG_SERVER_IP "sudo systemctl stop consoleapp.service"
        - scp backend/ms-config-server/target/ms-config-server-0.0.1-SNAPSHOT.jar ubuntu@$CONFIG_SERVER_IP:~/console-app/
        - ssh ubuntu@$CONFIG_SERVER_IP "sudo systemctl start consoleapp.service"
        - sleep 60
#  - EUREKA SERVER
        - ssh ubuntu@$EUREKA_SERVER_IP "sudo systemctl stop consoleapp.service"
        - scp backend/ms-eureka-server/target/ms-eureka-server-0.0.1-SNAPSHOT.jar ubuntu@$EUREKA_SERVER_IP:~/console-app/
        - ssh ubuntu@$EUREKA_SERVER_IP "sudo systemctl start consoleapp.service"
#  - API MOVIES
        - ssh ubuntu@$DEPLOY_SERVER_IP "sudo systemctl stop consoleapp.service"
        - scp backend/api-movie/target/api-movie-0.0.1-SNAPSHOT.jar ubuntu@$DEPLOY_SERVER_IP:~/console-app/
        - ssh ubuntu@$DEPLOY_SERVER_IP "sudo systemctl start consoleapp.service"
#  - API SERIES
        - ssh ubuntu@$DEPLOY_SERVER_IP "sudo systemctl stop series.service"
        - scp backend/api-series/target/api-series-0.0.1-SNAPSHOT.jar ubuntu@$DEPLOY_SERVER_IP:~/series-app/
        - ssh ubuntu@$DEPLOY_SERVER_IP "sudo systemctl start series.service"
#  - GATEWAY SERVER
        - ssh ubuntu@$GATEWAY_SERVER_IP "sudo systemctl stop consoleapp.service"
        - scp backend/ms-gateway-server/target/ms-gateway-server-0.0.1-SNAPSHOT.jar ubuntu@$GATEWAY_SERVER_IP:~/console-app/
        - ssh ubuntu@$GATEWAY_SERVER_IP "sudo systemctl start consoleapp.service"
#  - API USERS
        - ssh ubuntu@$USERS_SERVER_IP "sudo systemctl stop consoleapp.service"
        - scp backend/users-stack/ApiUsers/target/ApiUsers-0.0.1-SNAPSHOT.jar ubuntu@$USERS_SERVER_IP:~/console-app/
        - ssh ubuntu@$USERS_SERVER_IP "sudo systemctl start consoleapp.service"
