stages:
    - build
    - test
    - deploy

.backend-common:
    rules:
        - changes:
            - 'backend/**/*'

backend-build-job:
    stage: build
    extends: .backend-common
    image:  maven:latest
    script:
        - cd backend
        - cd api-movie
        - mvn clean install
        - cd target
    artifacts:
        expire_in: 1 week
        paths:
            - backend/api-movie/target/api-movie-0.0.1-SNAPSHOT.jar

backend-test-job:
    extends: .backend-common
    stage: test
    script:
        - echo "Testing backend"

backend-deploy-job:
    stage: deploy
    image: alpine:3.11
    extends: .backend-common
    before_script:
        - apk update && apk add openssh-client bash
        - mkdir -p ~/.ssh
        - eval $(ssh-agent -s)
        - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
        - touch ~/.ssh/config
        - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
        - ssh-keyscan -H $DEPLOY_SERVER_IP >> ~/.ssh/known_hosts
    script:
        - echo "Deploying started!"
        - ssh ubuntu@$DEPLOY_SERVER_IP "sudo systemctl stop consoleapp.service"
        - ls
        - cd backend
        - cd api-movie
        - cd target
        - ls
        - scp  api-movie-0.0.1-SNAPSHOT.jar ubuntu@$DEPLOY_SERVER_IP:~/console-app/
        - ssh ubuntu@$DEPLOY_SERVER_IP "sudo systemctl start consoleapp.service"
        - echo "Finished deploying the app."