server:
  port: ${PORT:8888}

spring:
  application:
    name: ms-config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitlab.com/adrian.ignaciomoncada/ecran.git
          default-label: develop
          force-pull: true
          search-paths: backend/configs/
          username: adrian.ignaciomoncada
          password: Ab4562651
