server:
  port: 8082

spring:
  application:
    name: users
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: pwd123
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://db.ctd.academy:3306/0723TDPI2N1C01LAED1021FT_GRUPO1?serverTimezone=UTC
    username: 0723TDPI2N1C01LAED1021FT_GRUPO1
    password: sae4Keix
  mail:
    host: smtp.gmail.com
    port: 587
    username: ecran.lat@gmail.com
    password: vwrmdffvfnpgxtqv
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      enabled: true
      show-details: always
  health:
    circuitbreakers:
      enabled: true

resilience4j:
  circuitbreaker:
    circuit-breaker-aspect-order: 1
    instances:
      movies:
        failure-rate-threshold: 50
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 10s
        sliding-window-type: COUNT_BASED
        sliding-window-size: 2
        minimum-number-of-calls: 1
        event-consumer-buffer-size: 10
  retry:
    retry-aspect-order: 2
    instances:
      movies:
        max-attempts: 3
        wait-duration: 2s
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 5

logging:
  level:
    com.ecran.api.users.data.MoviesServiceClient: DEBUG
    com.ecran.api.users.service.UsersServiceImpl: DEBUG
  pattern:
    level: "%5p [${spring.application.name}, %X{traceId:-}, %X{spanId:-}]"
  file:
    name: users.log

token:
  expiration_time: 7200000
  secret: "UhQbrtfsX8Q0S6MoJFjzQZthOK4Kbd5h7gH6YtT3jKreEjICe9OdpUULUaG50mbM"
login:
  url:
    path: /users/login


#movies:
#  url: http://movies/users/%s/movies