FROM eclipse-temurin:17-jdk-jammy
VOLUME /tmp
#COPY apiEncryptionKey.jks apiEncryptionKey.jks
#COPY UnlimitedJCEPolicyJDK8/* /usr/lib/jvm/java-1.8-openjdk/jre/lib/security/
COPY target/configServer-0.0.1-SNAPSHOT.jar ConfigServer.jar
ENTRYPOINT ["java","-Djava.security.edg=file:/dev/./urandom","-jar","ConfigServer.jar"]